---
abstract: 'A Catalyst Model for PayPal via Business::PayPal::API'
author:
  - 'Dean Hamstead <dean@fragfest.com.au>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300016, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Model-PayPal-API
requires:
  Business::PayPal::API: 0
  Catalyst::Model: 0
version: 0.31
